"""Constants for the ANEF API."""

from __future__ import annotations

from enum import Enum


class ServiceEnum(str, Enum):
    """Services handling the naturalisation request process."""

    PREFECTURE = 'PREFECTURE'
    ANEF = 'ANEF'
    SDANF = 'SDANF'
    SCEC = 'SCEC'
    DECRET = 'DECRET'


class APICodeEnum(int, Enum):
    """API return codes for the naturalisation request process."""

    DRAFT = 1
    VERIFICATION_FORMELLE_A_TRAITER = 2
    VERIFICATION_FORMELLE_EN_COURS = 3
    VERIFICATION_FORMELLE_MISE_EN_DEMEURE = 4
    CSS_MISE_EN_DEMEURE_A_AFFECTER = 5
    CSS_MISE_EN_DEMEURE_A_REDIGER = 6
    INSTRUCTION_A_AFFECTER = 7
    INSTRUCTION_RECEPISSE_COMPLETUDE_A_ENVOYER = 8
    INSTRUCTION_RECEPISSE_COMPLETUDE_A_ENVOYER_RETOUR_COMPLEMENT_A_TRAITER = 9
    INNTRUCTION_DATE_EA_A_FIXER = 10
    EA_DEMANDE_REPORT_EA = 11
    EA_EN_ATTENTE_EA = 12
    EA_CREA_A_VALIDER = 13
    PROP_DECISION_PREF_A_EFFECTUER = 14
    PROP_DECISION_PREF_EN_ATTENTE_RETOUR_HIERARCHIQUE = 15
    PROP_DECISION_PREF_PROP_A_EDITER = 16
    PROP_DECISION_PREF_EN_ATTENTE_RETOUR_SIGNATURE = 17
    CONTROLE_A_AFFECTER = 18
    CONTROLE_A_EFFECTUER = 19
    CONTROLE_EN_ATTENTE_PEC = 20
    CONTROLE_PEC_A_FAIRE = 21
    CONTROLE_TRANSMISE_POUR_DECRET = 22
    CONTROLE_EN_ATTENTE_RETOUR_HIERARCHIQUE = 23
    CONTROLE_DECISION_A_EDITER = 24
    CONTROLE_EN_ATTENTE_SIGNATURE = 25
    TRANSMIS_A_AC = 26
    A_VERIFIER_AVANT_INSERTION_DECRET = 27
    PRETE_POUR_INSERTION_DECRET = 28
    INSEREE_DANS_DECRET = 29
    DECRET_NATURALISATION_PUBLIC = 30
    DECRET_EN_PREPARATION = 31
    DECRET_A_QUALIFIER = 32
    DECRET_EN_VALIDATION = 33
    CSS_EN_DELAIS_RECOURS = 34
    DECISION_NEGATIVE_EN_DELAIS_RECOURS = 35
    IRRECEVABILITE_MANIFESTE = 36
    DECISION_NOTIFIEE = 37
    CSS_NOTIFIE = 38
    DEMANDE_EN_COURS_RAPO = 39
    CONTROLE_DEMANDE_NOTIFIEE = 40
    DECRET_PUBLIE = 41
    UNKNOWN = 999
